version: "3.8"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:12-alpine"
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "~/tmp/postgres/data:/var/lib/postgresql"
